### ISSUE TITLE
Saving SET weight in LBs shows as KG

### ISSUE THREAD

**Issue by zacklater** [nerdybeast/overcome-gravity#1]
When you are adding sets to your exercise you can select your weight in Lbs. After saving when I look a the exercise and sets it shows as Kg again.

**Comment by nerdybeast** [comment]
Haha, everything I do these days is in kilos so yeah... it defaults to kilos. My thought is to have the user select their "preference" and then save that under their settings (which doesn't exist yet) :/

**Comment by nerdybeast** [comment]
Fixed with https://github.com/nerdybeast/overcome-gravity/pull/4

**Comment by nerdybeast** [comment]
And with https://github.com/nerdybeast/overcome-gravity/pull/5
